-- AlterTable
ALTER TABLE "USER_PROFILES" ALTER COLUMN "birth_date" DROP NOT NULL,
ALTER COLUMN "document" DROP NOT NULL,
ALTER COLUMN "contact_preference" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL;
